import { redirect } from "next/navigation";
import { getServerAuthSession } from "~/server/auth";

import { Navbar } from "~/app/_components/navbar";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // If the user is not authenticated, redirect to the home page
  const session = await getServerAuthSession();
  if (!session) {
    redirect("/");
  }

  return (
    <>
      <Navbar />
      <div className="mt-14">{children}</div>
    </>
  );
}
